# Generated by Django 5.1.3 on 2024-11-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.TextField(max_length=30)),
                ('price', models.IntegerField()),
                ('tag', models.IntegerField()),
                ('availability', models.BooleanField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.TextField(max_length=20)),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('author', models.TextField(max_length=10)),
            ],
        ),
    ]
