# Generated by Django 5.2 on 2025-04-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
