# Generated by Django 5.2 on 2025-04-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0004_message_anonymous_alter_user_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.CharField(blank=True, default='none', max_length=255, null=True),
        ),
    ]
